### ISSUE TITLE
Mismatch error with kotlinx-datetime 0.7.x after upgrading to 2.7.0

### ISSUE THREAD

**Issue by KovshefulCoder** [kizitonwose/Calendar#621]
### Library and related version information:
 - Version: 2.7.0
 - Compose Multiplatform
 - **org.jetbrains.compose** version: 1.8.2
 - **kotlinx-datetime** version: 0.7.1

### Describe the bug**
After upgrading the libraries above, the KMP project fails to compile with type-mismatch errors. A typical example is:
```
private val com.kizitonwose.calendar.compose.CalendarState.curVisibleMonth: kotlinx.datetime.Month
    get() = this.firstVisibleMonth.yearMonth.month
```
"Return type mismatch: expected 'kotlinx.datetime.Month', actual 'java.time.Month'."

Downgrading kotlinx-datetime to 0.7.0 does not fix the problem, but rolling back to 0.6.2 allows the build to succeed.

### Possible source of issue

**This behavior likely from the alias changes introduced in kotlinx-datetime 0.7.0, [issue 96](https://github.com/Kotlin/kotlinx-datetime/issues/96)** 

### To Reproduce
1. In a Kotlin Multiplatform project that uses kizitonwose/calendar-compose upgrade to the versions listed above.
2. Sync and build the Android target.
3. Observe the compilation error

**Comment by KovshefulCoder** [comment]
@kizitonwose Works for me, tnx
