### ISSUE TITLE
Resource merge/build failure with AGP 8.x and target/compile API 36 due to android: attrs in custom styleables (attrs.xml)

### ISSUE THREAD

**Issue by dev-abcdevelopers** [kizitonwose/Calendar#622]
### Library information:
 - Version: [e.g. 2.7.0]
 - View or Compose module: [View]

### Describe the bug**
When upgrading com.kizitonwose.calendar:view from version 2.4.1 to 2.7.0, the build fails on Windows (and potentially other platforms) when using Android Gradle Plugin (AGP) 8.x and setting compileSdk and targetSdk to 36 (or 34+).
The error is related to illegal characters (<:>) in the resource path during resource merging, and is caused by the presence of android: namespace attributes (like android:inputType) declared inside custom declare-styleable blocks in attrs.xml.
This is now disallowed in AGP 8.x and API 34+, causing builds to fail.

Sample error message:
Resource compilation failed (Failed to compile values resource file ... Illegal char <:> at index ... com.kizitonwose.calendar...:/values/values.xml)

### To Reproduce (if applicable)
1. Update the dependency to com.kizitonwose.calendar:view:2.7.0
2. Set compileSdk and targetSdk to 36 (or 34+)
3. Use Android Gradle Plugin 8.x (8.11.0)
4. Build the project on Windows

### Expected behavior (if applicable)
The project should build successfully and the library should be usable as before.

### Screenshots? (if applicable)
Resource compilation failed (Failed to compile values resource file ... Illegal char <:> at index ... com.kizitonwose.calendar...:/values/values.xml)

### Additional information
- The issue occurs only with library versions 2.7.0+ and AGP 8.x / API 36+.
- Downgrading to com.kizitonwose.calendar:view:2.4.1 or removing the use of android: namespace attributes from custom styleables in attrs.xml allows the build to succeed.
- Reference: [Android docs on custom attributes](https://developer.android.com/reference/android/content/res/TypedArray) (should not declare android: attributes in custom styleables)

- AGP 8.x and Android 14+ (API 34+) enforce stricter resource merging and path rules.
- Please update attrs.xml to remove any android: attributes from custom styleables to restore compatibility.

**Comment by dev-abcdevelopers** [comment]
It would fail on Mac, too.
