### ISSUE TITLE
Crash on Calendar Setup on Release Build Variant

### ISSUE THREAD

**Issue by Broz3r** [kizitonwose/Calendar#249]
Hello,

I am facing an error with the 1.0.0 version of the library when I setup my calendar.
The crash only happens in release build variants and seems to be related to #209.

Here the crashlog :
```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method compareTo(Lj$/time/YearMonth;)I in class Lj$/time/YearMonth; or its super classes (declaration of 'j$.time.YearMonth' appears in /data/app/pro.leanor.app.staging-d0SAjD2iDbnaMpbwZSE4pQ==/base.apk:classes2.dex)
       at com.kizitonwose.calendarview.model.MonthConfig$Companion.generateBoundedMonths(MonthConfig.kt:49)
       at com.kizitonwose.calendarview.model.MonthConfig.<init>(MonthConfig.kt:23)
       at com.kizitonwose.calendarview.CalendarView.setup(CalendarView.kt:668)
       [...]
```

Gradle Version: `4.1.1`
Kotlin Version: `1.4.21`
Min SDK: `21` - Target SDK: `29`
CoreLibraryDesugaring Version : `1.1.1`

**Comment by kizitonwose** [comment]
I am really not sure what causes this. Can you try using the same version of desugar in the library in your project?

**Comment by Broz3r** [comment]
Okay, this seems to work with the 1.0.10 version of desurgar.

But to achieve this, I had to remove completely desugar from my project, update my min SDK version to 26 to allow the use of the Java 8 methods, then readd a previous version of desugar and return to my previous min SDK version. Just downgrade the version of desugar do not fix the crash (even with a cleaned cash). 
This is odd, but the issue is certainly on desugar newest version.

Anyway, thank you for your reply and for this great library !

**Comment by Broz3r** [comment]
I have the same issue with the 1.0.10 version of desugar :/

**Comment by Broz3r** [comment]
I ran several tests to see where is the issue but I could not find any solution. This problem drives me crazy...

But I can tell you the issue is not coming from the library: I clone the repo and change the Gradle settings and dependencies version and the sample project did not crash in release build variant on any cases.
I do not know how, but I think there is an issue between my project settings and the lib' settings, because desugar methods like `YearMonth.comparTo` are available in my code and do not crash on Release build.

I am running out of time to investigate further, so I downgraded the lib' to the 0.3.5 version (before desugar implementation). If someone faces the same issue, I will be happy to help.

Thank you for this great lib and the support !

**Comment by kizitonwose** [comment]
This is rather unfortunate. Hopefully, someone can provide repro steps.

**Comment by Turubaev** [comment]
Had almost the same issue, which was resolved when returned testCoverageEnabled to true inside release buildTypes. Somehow non-debuggable APK (i.e. testCoverageEnabled = false) didn't include all methods into the dex files. 
In case of debuggable APK there was about 40-50 dex files, while non-debuggable APK was containing about 10 dex files.

**Comment by AlexSkvor** [comment]
Faced very similar issue today, found a solution for my case. I'm pretty sure it is just the same as #271 .

So I got `java.lang.NoSuchMethodError` and only in Release build too.
The reason was proguard obviously.

I had following code:
`calendarView.monthViewClass = CalendarMonthView::class.java.name`

But for release build proguard was obfuscating my class `CalendarMonthView` while it should be created by name inside library:
```
val userRoot = viewConfig.monthViewClass?.let {
            val customLayout = (Class.forName(it)
                .getDeclaredConstructor(Context::class.java)
                .newInstance(context) as ViewGroup)
            customLayout.apply {
                setupRoot(this)
                addView(rootLayout)
            }
        } ?: rootLayout.apply { setupRoot(this) }
```
 (Code from com.kizitonwose.calendarview.ui.CalendarAdapter)
 
 So I just added rule for proguard:
```
-keep class com.my.project.calendar.CalendarMonthView {
    <init>(android.content.Context);
}
```

And it solved the issue for me. Hope this will help someone else in future!

**Comment by kizitonwose** [comment]
Closing this as it's been a while now.
